# build node 20 image
FROM node:20-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
RUN npm ci --only=production

# Bundle app source
COPY ./dist /app/dist
COPY ./env-cmdrc /app/.env-cmdrc

EXPOSE 8000

CMD npm run serve