# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CD

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    # Checkout the code from the GitHub repository
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          react_client/build
          react_client/DockerFile
          react_client/.dockerignore
          server/DockerFile
          server/.dockerignore
          server/dist
          server/package.json
          server/src/uploads
          docker-compose.yml
    - name: Docker compose up
      run: |
        sudo docker compose up -d