# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Docker compose down
      run: |
        sudo docker compose down
        sudo docker rmi -f $(docker images -aq)
    # Checkout the code from the GitHub repository
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: production
        sparse-checkout: |
          react_client/build
          react_client/DockerFile --skip-checks
          react_client/.dockerignore --skip-checks
          server/DockerFile --skip-checks
          server/.dockerignore --skip-checks
          server/dist
          server/package.json --skip-checks
          docker-compose.yml --skip-checks
    - name: Docker compose up
      run: |
        sudo docker compose up -d