# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "production" ]
    
  pull_request:
    branches: [ "production" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the code from the GitHub repository
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: production
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    # Install dependencies and run tests for the client application
    - name: Install and build Client
      working-directory: ./react_client
      run: |
        npm ci
        npm run build
    # Install dependencies, export environment variables to be used by application and run tests for the server application
    - name: Install and build Server
      working-directory: ./server
      run: |
        npm ci
        npm run build
    - name: Commit Build
      run: |
        if [[ `git status --porcelain` ]]; then
            git config --global user.name "dip7501686040"
            git config --global user.email "dip7501686040@gmail.com"
            git add -f ./server/dist ./react_client/build
            git commit -m "added build"
            git push origin HEAD:production --force
          else
            echo "WARNING: No changes were detected."
          fi